Update @ 03-11-2026 01:06

diff --git a/bin/box b/bin/box
--- a/bin/box
+++ b/bin/box
@@ -21,26 +21,26 @@ RST=$'\x1b[0m'
 
 # example: repeat-char '=' 50
 repeat-char() {
-	local char=$1
-	local n=$2
-	local s
-	printf -v s "%${n}s"
-	echo -n "${s// /$char}"
+  local char=$1
+  local n=$2
+  local s
+  printf -v s "%${n}s"
+  echo -n "${s// /$char}"
 }
 
 # example: cat thing.txt | strip-ansi
 strip-ansi() (
-	shopt -s extglob
-	local IFS=
-	local line
-	while read -r line || [[ -n $line ]]; do
-		printf '%s\n' "${line//$'\e'[\[(]*([0-9;])[@-n]/}"
-	done
+  shopt -s extglob
+  local IFS=
+  local line
+  while read -r line || [[ -n $line ]]; do
+    printf '%s\n' "${line//$'\e'[\[(]*([0-9;])[@-n]/}"
+  done
 )
 
 usage() {
-	local prog=${0##*/}
-	cat <<-EOF
+  local prog=${0##*/}
+  cat <<-EOF
 	Usage: $prog [-t title] [...] < input
 
 	Create a unicode or ASCII box around input text (from stdin)
@@ -58,8 +58,8 @@ usage() {
 }
 
 fatal() {
-	echo '[FATAL]' "$@" >&2
-	exit 1
+  echo '[FATAL]' "$@" >&2
+  exit 1
 }
 
 title=
@@ -70,17 +70,41 @@ color=''
 tcolor=
 theme='unicode'
 while [[ -n $1 ]]; do
-	case "$1" in
-		-h|--help) usage; exit 0;;
-		-bc) color=$2; shift 2;;
-		-tc) tcolor=$2; shift 2;;
-		-vp) vpadding=$2; shift 2;;
-		-hp) hpadding=$2; shift 2;;
-		-s) sep=$2; shift 2;;
-		-t) title=$2; shift 2;;
-		-T) theme=$2; shift 2;;
-		*) fatal "invalid argument: $1";;
-	esac
+  case "$1" in
+  -h | --help)
+    usage
+    exit 0
+    ;;
+  -bc)
+    color=$2
+    shift 2
+    ;;
+  -tc)
+    tcolor=$2
+    shift 2
+    ;;
+  -vp)
+    vpadding=$2
+    shift 2
+    ;;
+  -hp)
+    hpadding=$2
+    shift 2
+    ;;
+  -s)
+    sep=$2
+    shift 2
+    ;;
+  -t)
+    title=$2
+    shift 2
+    ;;
+  -T)
+    theme=$2
+    shift 2
+    ;;
+  *) fatal "invalid argument: $1" ;;
+  esac
 done
 
 # horizontal padding
@@ -88,37 +112,37 @@ hpadding=$(repeat-char ' ' "$hpadding")
 
 # these variables are named for the junctions they connect
 case "$theme" in
-	unicode)
-		WE='─'
-		NS='│'
-		SE='┌'
-		NE='└'
-		SW='┐'
-		NW='┘'
-		SWE='┬'
-		NWE='┴'
-		;;
-	ascii)
-		WE='-'
-		NS='|'
-		SE='+'
-		NE='+'
-		SW='+'
-		NW='+'
-		SWE='+'
-		NWE='+'
-		;;
-	plain)
-		WE=' '
-		NS=' '
-		SE=' '
-		NE=' '
-		SW=' '
-		NW=' '
-		SWE=' '
-		NWE=' '
-		;;
-	*) fatal "invalid theme name: $theme";;
+unicode)
+  WE='─'
+  NS='│'
+  SE='┌'
+  NE='└'
+  SW='┐'
+  NW='┘'
+  SWE='┬'
+  NWE='┴'
+  ;;
+ascii)
+  WE='-'
+  NS='|'
+  SE='+'
+  NE='+'
+  SW='+'
+  NW='+'
+  SWE='+'
+  NWE='+'
+  ;;
+plain)
+  WE=' '
+  NS=' '
+  SE=' '
+  NE=' '
+  SW=' '
+  NW=' '
+  SWE=' '
+  NWE=' '
+  ;;
+*) fatal "invalid theme name: $theme" ;;
 esac
 
 # read the entire input first
@@ -129,31 +153,31 @@ max_width=0
 max_cols=()
 num_cols=1
 for line in "${input[@]}"; do
-	s=${line//$sep}
-	len=${#s}
+  s=${line//$sep/}
+  len=${#s}
 
-	if ((len > max_width)); then
-		max_width=$len
-	fi
+  if ((len > max_width)); then
+    max_width=$len
+  fi
 
-	# count how many cells there are
-	if [[ -n $sep ]]; then
-		seps=${line//[^$sep]}
-		num_cols=$((${#seps} + 1))
-	else
-		num_cols=1
-	fi
+  # count how many cells there are
+  if [[ -n $sep ]]; then
+    seps=${line//[^$sep]/}
+    num_cols=$((${#seps} + 1))
+  else
+    num_cols=1
+  fi
 
-	IFS=$sep read -ra cells <<< "$line"
-	for ((i = 0; i < num_cols; i++)); do
-		cell=$hpadding${cells[i]}$hpadding
-		cell_stripped=$(strip-ansi <<< "$cell")
+  IFS=$sep read -ra cells <<<"$line"
+  for ((i = 0; i < num_cols; i++)); do
+    cell=$hpadding${cells[i]}$hpadding
+    cell_stripped=$(strip-ansi <<<"$cell")
 
-		cell_len=${#cell_stripped}
-		if ((cell_len > max_cols[i])); then
-			max_cols[i]=$cell_len
-		fi
-	done
+    cell_len=${#cell_stripped}
+    if ((cell_len > max_cols[i])); then
+      max_cols[i]=$cell_len
+    fi
+  done
 done
 ((max_width += num_cols - 1))
 
@@ -163,65 +187,65 @@ line=$color$SE$WE$RST
 line+=$tcolor$title$RST$color
 offset=$((${#title} + 1))
 for ((i = 0; i < num_cols; i++)); do
-	max_len=${max_cols[i]}
-	copy=$max_len
-	((i < num_cols - 1)) && ((copy++))
+  max_len=${max_cols[i]}
+  copy=$max_len
+  ((i < num_cols - 1)) && ((copy++))
 
-	if ((offset > 0)); then
-		((max_len -= offset))
-	fi
+  if ((offset > 0)); then
+    ((max_len -= offset))
+  fi
 
-	if ((max_len < 0)); then
-		((offset -= copy))
-		continue
-	fi
-	offset=0
+  if ((max_len < 0)); then
+    ((offset -= copy))
+    continue
+  fi
+  offset=0
 
-	line+=$(repeat-char "$WE" "$max_len")
-	((i < num_cols - 1)) && line+=$SWE
+  line+=$(repeat-char "$WE" "$max_len")
+  ((i < num_cols - 1)) && line+=$SWE
 done
 line+=$SW$RST
 echo "$line"
 
 # add vertical padding (top)
 for ((i = 0; i < vpadding; i++)); do
-	s=$(repeat-char "$sep" "$num_cols")
-	input=("$s" "${input[@]}" "$s")
+  s=$(repeat-char "$sep" "$num_cols")
+  input=("$s" "${input[@]}" "$s")
 done
 
 # process each row
 for line in "${input[@]}"; do
-	IFS=$sep read -ra cells <<< "$line"
+  IFS=$sep read -ra cells <<<"$line"
 
-	# process each cell
-	line=$color$NS$RST
-	for ((i = 0; i < num_cols; i++)); do
-		cell=$hpadding${cells[i]}$hpadding
-		cell_stripped=$(strip-ansi <<< "$cell")
-		max_len=${max_cols[i]}
-		len=${#cell_stripped}
+  # process each cell
+  line=$color$NS$RST
+  for ((i = 0; i < num_cols; i++)); do
+    cell=$hpadding${cells[i]}$hpadding
+    cell_stripped=$(strip-ansi <<<"$cell")
+    max_len=${max_cols[i]}
+    len=${#cell_stripped}
 
-		# write the cell data
-		line+=$cell
+    # write the cell data
+    line+=$cell
 
-		# pad it with spaces (left-align)
-		line+=$(repeat-char ' ' "$((max_len - len))")
+    # pad it with spaces (left-align)
+    line+=$(repeat-char ' ' "$((max_len - len))")
 
-		# add the terminator char
-		line+=$color$NS$RST
-	done
+    # add the terminator char
+    line+=$color$NS$RST
+  done
 
-	# print the final line
-	echo "$line"
+  # print the final line
+  echo "$line"
 done
 
 # print footer
 line=$color
 line+=$NE
 for ((i = 0; i < num_cols; i++)); do
-	max_len=${max_cols[i]}
-	line+=$(repeat-char "$WE" "$max_len")
-	((i < num_cols - 1)) && line+=$NWE
+  max_len=${max_cols[i]}
+  line+=$(repeat-char "$WE" "$max_len")
+  ((i < num_cols - 1)) && line+=$NWE
 done
 line+=$NW
 line+=$RST
