Update @ 05-25-2025 05:34

diff --git a/bin/pkgsearch b/bin/pkgsearch
--- a/bin/pkgsearch
+++ b/bin/pkgsearch
@@ -34,9 +34,10 @@ has() {
     verbose=1
     shift
   fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( "$verbose" > 0 )) && err "$c not found"
+  for c; do
+    c="${c%% *}"
+    if ! command -v "$c" &>/dev/null; then
+      (("$verbose" > 0)) && err "$c not found"
       return 1
     fi
   done
@@ -46,14 +47,14 @@ select_from() {
   local cmd='command -v'
   for a; do
     case "$a" in
-      -c)
-        cmd="$2"
-        shift 2
-        ;;
+    -c)
+      cmd="$2"
+      shift 2
+      ;;
     esac
   done
   for c; do
-    if $cmd "${c%% *}" &> /dev/null; then
+    if $cmd "${c%% *}" &>/dev/null; then
       echo "$c"
       return 0
     fi
@@ -71,16 +72,16 @@ fzf() {
 install() {
   local pkgs count
   mapfile -t pkgs
-  (( ${#pkgs} > 0 )) || exit
+  ((${#pkgs} > 0)) || exit
   count="${#pkgs[@]} package"
-  (( ${#pkgs[@]} > 1 )) && count+='s'
+  ((${#pkgs[@]} > 1)) && count+='s'
   printf "installing %s: %s\n" "$count" "${pkgs[*]}"
-  $1 "${pkgs[@]}" < /dev/tty
+  $1 "${pkgs[@]}" </dev/tty
 }
 
 debian() {
   fzf --preview='apt-cache show {1}' \
-      --query="$1" \
+    --query="$1" \
     < <(apt-cache search '.*' | sort |
       sed -u -r "s|^([^ ]+)|${c_green}\1${c_reset}|") |
     cut -d' ' -f1 |
@@ -92,8 +93,9 @@ arch() {
   search='pacman'
   [[ -n "$1" ]] && search=$(select_from 'paru' 'yay' 'pacaur' 'trizen' 'yaourt' 'packer' 'apacman' 'pacman')
   packages=$(fzf --preview="$search -Si {2}" \
-    < <( $search -Ss "$1" |
-      gawk '{
+    < <(
+      $search -Ss "$1" |
+        gawk '{
         getline descr;
         sub(/ */,"", descr);
         repo = blue "[" gensub(/\/.*/, "", 1) "]" reset;
@@ -103,14 +105,14 @@ arch() {
       }' blue="$c_blue" green="$c_green" reset="$c_reset"
     ) | cut -d' ' -f2)
   [[ "$search" = "pacman" ]] && search="sudo pacman"
-  install "$search -S" <<< "$packages"
+  install "$search -S" <<<"$packages"
 }
 
 void() {
   local package_list packagename='{ sub(/-[^\-]*$/, "", $2); print $2 }'
   package_list=$(xbps-query -Rs '' | sort)
   fzf --preview="p=\$(awk \"$packagename\" <<< {}); xbps-query -Rx \$p" \
-      --query="$1" <<< "$package_list" |
+    --query="$1" <<<"$package_list" |
     awk "$packagename" |
     install 'xbps-install -S'
 }
@@ -124,9 +126,15 @@ fedora() {
 
 while true; do
   case "$1" in
-    -h|--help) usage; exit ;;
-    -p|--preview) preview_pos="$2"; shift 2 ;;
-    *) break
+  -h | --help)
+    usage
+    exit
+    ;;
+  -p | --preview)
+    preview_pos="$2"
+    shift 2
+    ;;
+  *) break ;;
   esac
 done
 
@@ -140,9 +148,9 @@ if [[ -r /etc/os-release ]]; then
 fi
 
 case "$distro" in
-  debian|ubuntu) debian "$request" ;;
-  arch) arch "$request" ;;
-  void) void "$request" ;;
-  fedora) fedora "$request" ;;
-  *) die 'unknown distro :(' ;;
+debian | ubuntu) debian "$request" ;;
+arch) arch "$request" ;;
+void) void "$request" ;;
+fedora) fedora "$request" ;;
+*) die 'unknown distro :(' ;;
 esac
