Update @ 11-21-2025 13:40

diff --git a/bin/pkgs b/bin/pkgs
--- a/bin/pkgs
+++ b/bin/pkgs
@@ -14,6 +14,9 @@ usage() {
   LESS=-FEXR less <<HELP
 pkgsearch [options] [query]
   lists and installs packages from your distro's repositories
+
+  without any arguments pkgsearch will list all available packages from your cache
+  note: on Arch Linux you must pass a string to query the AUR
 HELP
 }
 
@@ -31,12 +34,32 @@ has() {
     verbose=1
     shift
   fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( "$verbose" > 0 )) && err "$c not found"
+  for c; do
+    c="${c%% *}"
+    if ! command -v "$c" &>/dev/null; then
+      (("$verbose" > 0)) && err "$c not found"
       return 1
     fi
   done
+}
+
+select_from() {
+  local cmd='command -v'
+  for a; do
+    case "$a" in
+    -c)
+      cmd="$2"
+      shift 2
+      ;;
+    esac
+  done
+  for c; do
+    if $cmd "${c%% *}" &>/dev/null; then
+      echo "$c"
+      return 0
+    fi
+  done
+  return 1
 }
 
 fzf() {
@@ -49,31 +72,75 @@ fzf() {
 install() {
   local pkgs count
   mapfile -t pkgs
-  (( ${#pkgs} > 0 )) || exit
+  ((${#pkgs} > 0)) || exit
   count="${#pkgs[@]} package"
-  (( ${#pkgs[@]} > 1 )) && count+='s'
+  ((${#pkgs[@]} > 1)) && count+='s'
   printf "installing %s: %s\n" "$count" "${pkgs[*]}"
-  $1 "${pkgs[@]}" < /dev/tty
+  $1 "${pkgs[@]}" </dev/tty
 }
 
-is_installed() {
-  dpkg -l "$1" &> /dev/null
+termux() {
+  fzf --preview='pkg show {1}' \
+    --query="$1" \
+    < <(apt-cache pkgnames - "$@" | sort) | install "$(select_from 'pkg' 'apt' 'apt-get') install"
 }
 
-aptpkg() {
+debian() {
   fzf --preview='apt-cache show {1}' \
-      --query="$1" \
+    --query="$1" \
     < <(apt-cache search '.*' | sort |
       sed -u -r "s|^([^ ]+)|${c_green}\1${c_reset}|") |
     cut -d' ' -f1 |
-    install "pkg install -y"
+    install "sudo $(select_from 'apt' 'aptitude' 'apt-get') install"
+}
+
+arch() {
+  local search packages
+  search='pacman'
+  [[ -n "$1" ]] && search=$(select_from 'paru' 'yay' 'pacaur' 'trizen' 'yaourt' 'packer' 'apacman' 'pacman')
+  packages=$(fzf --preview="$search -Si {2}" \
+    < <(
+      $search -Ss "$1" |
+        gawk '{
+        getline descr;
+        sub(/ */,"", descr);
+        repo = blue "[" gensub(/\/.*/, "", 1) "]" reset;
+        name = green gensub(/.*\//, "", 1, $1) reset;
+        info = gensub(/[^ ]* /, "", 1);
+        print repo, name, info, descr;
+      }' blue="$c_blue" green="$c_green" reset="$c_reset"
+    ) | cut -d' ' -f2)
+  [[ "$search" = "pacman" ]] && search="sudo pacman"
+  install "$search -S" <<<"$packages"
+}
+
+void() {
+  local package_list packagename='{ sub(/-[^\-]*$/, "", $2); print $2 }'
+  package_list=$(xbps-query -Rs '' | sort)
+  fzf --preview="p=\$(awk \"$packagename\" <<< {}); xbps-query -Rx \$p" \
+    --query="$1" <<<"$package_list" |
+    awk "$packagename" |
+    install 'xbps-install -S'
+}
+
+fedora() {
+  fzf --query="$*" --preview='p={}; p="${p%% *}"; dnf -q info "${p%.*}"' \
+    < <(dnf -qC repoquery --qf "${c_green}%{name} ${c_reset} - %{summary}" \*) |
+    awk '{ package=$1; sub(/\.\S+/, "", package); print package }' |
+    install 'sudo dnf install'
 }
 
 while true; do
   case "$1" in
-    -h|--help) usage; exit ;;
-    -p|--preview) preview_pos="$2"; shift 2 ;;
-    *) break
+  -h | --help)
+    usage
+    exit
+    ;;
+  -p | --preview)
+    preview_pos="$2"
+    shift 2
+    ;;
+  *) break ;;
   esac
 done
 
@@ -81,7 +148,19 @@ has -v fzf gawk || die
 
 request="$*"
 
-aptpkg "$request"
+if [[ -r /etc/os-release ]]; then
+  distro=$(awk -F'=' '"NAME" == $1 { gsub("\"", "", $2); print tolower($2); }' /etc/os-release)
+  distro="${distro%% *}"
+elif [[ -r "$TERMUX__PREFIX/etc/os-release" ]]; then
+  distro=$(awk -F'=' '"NAME" == $1 { gsub("\"", "", $2); print tolower($2); }' "$TERMUX__PREFIX/etc/os-release")
+  distro="${distro%% *}"
+fi
 
-# TODO: homebrew: brew desc -s
-# sample output: https://pastebin.com/raw/3frRf6C7
+case "$distro" in
+debian | ubuntu) debian "$request" ;;
+arch) arch "$request" ;;
+void) void "$request" ;;
+fedora) fedora "$request" ;;
+termux) termux "$request" ;;
+*) die 'unknown distro :(' ;;
+esac
