Update @ 09-12-2024 16:48

diff --git a/bin/setlink b/bin/setlink
--- a/bin/setlink
+++ b/bin/setlink
@@ -1,111 +1,98 @@
 #!/bin/bash
 
-# Function to display usage
-usage() {
-  echo "Usage: $0 -b <base> -t <target> [-v] [-i]"
-  echo "  -b <base>    Base directory for the symbolic link."
-  echo "  -t <target>  Target directory for the symbolic link."
-  echo "  -i           Interactive mode. Prompt the user to overwrite the target if it already exists."
-  exit 1
-}
+# Synopsis: Symbolic link a file or directory to another file or directory.
 
-# Parse parameters
-while getopts "b:t:vi" opt; do
-  case $opt in
-    b) base="$OPTARG" ;;
-    t) target="$OPTARG" ;;
-    i) interactive=true ;;
-    *) usage ;;
-  esac
-done
+# Parameters
+base=$1
+target=$2
 
-# Check mandatory parameters
-if [ -z "$base" ] || [ -z "$target" ]; then
-  usage
-fi
-
-# Resolve full paths
+# Resolve paths
 base=$(realpath "$base")
 target=$(realpath "$target")
 
-# Define colors
-basedircolor="\033[34m"  # Blue
-baseleafcolor="\033[32m"  # DarkGreen
-targetdircolor="\033[34m"  # Blue
-targetleafcolor="\033[36m"  # DarkCyan
-arrowcolor="\033[90m"  # DarkGray
-arrow="  -->  "
-# dotcolor="\033[32m"  # Green
-devcolor="\033[35m"  # Magenta
-# homecolor="\033[34m"  # Blue
-resetcolor="\033[0m"
-
-# Define backup directory and file name
-backupDir="$HOME/backups"
-bakDate=$(date +"%m-%d-%Y-%H.%M.%S")
-backupFileName="$(basename "$target").$bakDate.bak"
-backupFilePath="$(dirname "$target")/$backupFileName"
-
-
-# Check if base path exists
+# Check if base exists
 if [ ! -e "$base" ]; then
-  echo -e "${resetcolor}"
-  echo -e " $base does not exist." >&2
-  echo -e "${resetcolor}"
+  echo ""
+  echo -e "\e[31m $base does not exist.\e[0m"
   exit 1
 fi
 
-# Function to create backup
+# Function to create a backup
 create_backup() {
-  if [ ! -d "$backupDir" ]; then
-    echo -e "${resetcolor}"
-    echo -e "${devcolor}  Creating backup directory: ${resetcolor}$backupDir"
-    mkdir -p "$backupDir"
+  backup_dir="$HOME/backups"
+  bak_date=$(date +"%m-%d-%Y-%H-%M")
+  target_leaf=$(basename "$target")
+  backup_file_name="$target_leaf.$bak_date.bak"
+  if [ ! -d "$backup_dir" ]; then
+    echo -e "\e[33m  Creating backup directory: \e[0m\c"
+    mkdir -p "$backup_dir"
+    echo -e "\e[37m$backup_dir\e[0m"
   fi
-  mv "$target" "$backupFilePath"
-  mv "$backupFilePath" "$backupDir"
-  echo -e "${resetcolor}"
-  echo -e "${arrowcolor} Backup: ${resetcolor}$backupDir/$backupFileName"
-  echo -e "${resetcolor}"
+  echo ""
+  echo -e "\e[33m Backup: \e[0m\c"
+  backup_file_path=$(dirname "$target")/$backup_file_name
+  mv "$target" "$backup_file_path"
+  mv "$backup_file_path" "$backup_dir"
+  echo -e "\e[37m$backup_dir/$backup_file_name\e[0m"
 }
 
-# Function to create symbolic link
+# Function to create a symbolic link
 create_link() {
   ln -s "$base" "$target"
-  echo -e "${basedircolor} $(dirname "$base")${baseleafcolor}$(basename "$base")${arrowcolor}$arrow${targetdircolor}$(dirname "$target")/${targetleafcolor}$(basename "$target")${resetcolor}"
-  echo -e "${resetcolor}"
+
+  arrow="  -->  "
+  basepath=$(realpath "$base")
+  basedir=$(dirname "$basepath")
+  baseleaf=$(basename "$basepath")
+  basedircolor="\e[34m"
+  targetpath=$(realpath "$target")
+  targetdir=$(dirname "$targetpath")
+  targetleaf=$(basename "$targetpath")
+  targetdircolor="\e[34m"
+
+  if [ "$basedir" == "$DOTS" ] || [ "$(dirname "$basepath")" == "$DOTFILES" ]; then
+    basedircolor="\e[35m"
+    basedir="   "
+  else
+    basedir=" $basedir/"
+  fi
+
+  targetdir="$targetdir/"
+  echo ""
+  echo -e "$basedircolor$basedir\e[36m$baseleaf\e[90m$arrow$targetdircolor$targetdir\e[36m$targetleaf\e[0m"
+  echo ""
 }
 
-# Check if target path exists
+# Check if target exists
 if [ ! -e "$target" ]; then
-  echo -e "${resetcolor}"
   create_link
   exit 0
 fi
 
-# Handle interactive mode and create link
-if [ -e "$target" ]; then
-  if [ "$(readlink "$target")" = "$base" ]; then
-    echo -e "${arrowcolor} $(dirname "$base")$(basename "$base") = $(dirname "$target")/$(basename "$target")${resetcolor}"
-    exit 0
-  else
-    if [ "$interactive" = true ]; then
-      echo -e "${resetcolor}"
-      echo -e "${devcolor} $(readlink -f "$target") ${resetcolor}already exists."
-      echo -e "${arrowcolor} Overwrite? ${resetcolor}[Y/n]"
-      read -r userChoice
-      if [ "$userChoice" = "Y" ] || [ "$userChoice" = "y" ] || [ -z "$userChoice" ]; then
+# Try to create the symbolic link
+{
+  if [ -e "$target" ]; then
+    if [ "$(readlink "$target")" == "$base" ]; then
+      echo ""
+      echo -e "\e[90m $base and $target already linked.\e[0m"
+      exit 0
+    else
+      echo ""
+      echo -e "\e[35m $(realpath "$target") \e[0m\c"
+      echo -e "\e[37malready exists. \e[0m"
+      echo -e "\e[36m Create backup file and symlink? \e[0m\c"
+      read -p "[Y/n] " user_choice
+      if [ "$user_choice" == "Y" ] || [ "$user_choice" == "y" ] || [ -z "$user_choice" ]; then
         create_backup
         create_link
       else
-        echo -e "${resetcolor}"
-        echo -e " Operation cancelled." >&2
-        echo -e "${resetcolor}"
-        exit 1
+        echo ""
+        echo -e "\e[31m Operation cancelled.\e[0m"
+        echo ""
+        exit 0
       fi
-    else
-      create_backup
-      create_link
     fi
   fi
-fi
+} || {
+  echo " Failed to create symbolic link: $?"
+}
