Sync via termux on 2026-05-01 13:06

diff --git a/scripts/blastoff b/scripts/blastoff
--- a/scripts/blastoff
+++ b/scripts/blastoff
@@ -108,208 +108,203 @@ STARSHIP_CONFIG="$STARSHIP_DIR/starship.toml"
 STARSHIP_THEMES="$STARSHIP_DIR/themes"
 PADDING="  "
 
-function linebreak {
-    echo -e "${c_reset}"
+linebreak() {
+  echo -e "${c_reset}"
 }
 
-function starship_pre_check {
-    if [[ ! -d "$STARSHIP_THEMES" ]]; then
-        echo "Starship themes directory not found: $STARSHIP_THEMES"
-        return 1
+starship_pre_check() {
+  if [[ ! -d "$STARSHIP_THEMES" ]]; then
+    echo "Starship themes directory not found: $STARSHIP_THEMES"
+    return 1
+  fi
+  if [[ ! -f "$STARSHIP_CONFIG" ]]; then
+    echo "Starship config file not found: $STARSHIP_CONFIG"
+    return 1
+  fi
+  return 0
+}
+
+bannerline() {
+  local dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+  local linenumber="$1"
+  cat "$dir/blastoffbanner" | sed -n "${linenumber}p"
+}
+
+banner() {
+  local line1="$(bannerline '1')"
+  local line2="$(bannerline '2')"
+  local line3="$(bannerline '3')"
+  printf "%-33s%s${c_reset}\n" "$PADDING" "$l1"
+  printf "%-33s%s${c_reset}\n" "$PADDING" "$l2"
+  printf "%s${bannerbgcolor}%s%s%s${c_reset}\n" "$PADDING" "$PADDING" "$line1" "$l3"
+  printf "%s${bannerbgcolor}%s%s%s${c_reset}\n" "$PADDING" "$PADDING" "$line2" "$l4"
+  printf "%s${bannerbgcolor}%s%s%s${c_reset}\n" "$PADDING" "$PADDING" "$line3" "$l4"
+}
+
+write_tagline() {
+  local tagline="$1"
+  printf "%s${taglinebgcolor}%s${taglinecolor}%-31s%s${c_reset}\n${c_reset}" "$PADDING" "$PADDING" "$tagline" "$l6"
+  printf "%-33s%s${c_reset}\n" "$PADDING" "$l7"
+}
+
+write_usage() {
+  local usage="$1"
+  local cmd="$2"
+  local left="$3"
+  local opts="$4"
+  local right="$5"
+  printf "%-3s${usagecolor}%-30s${c_reset}${rocketcolor}%s${c_reset}\n" "$PADDING" "$usage" "$l8"
+  printf "%-5s${cmdcolor}%s${c_reset} ${bracketcolor}%s${c_reset}${optscolor}%s${c_reset}${bracketcolor}%-11s${c_reset}${rocketcolor}%s${c_reset}\n" "$PADDING" "$cmd" "$left" "$opts" "$right" "$l9"
+}
+
+write_params() {
+  local paramtext="$1"
+  local desctext="$2"
+  printf "${PADDING}${parambgcolor}${paramcolor}${PADDING}%-12s${PADDING}${descbgcolor}${desccolor}${PADDING}%-26s${PADDING}${c_reset}\n" "$paramtext" "$desctext"
+}
+
+write_header() {
+  local headertext="$1"
+  printf "${PADDING}${headerbgcolor}${themeheadercolor}%s${c_reset}\n" "$headertext"
+}
+
+write_bullet() {
+  local bullet="$1"
+  printf "${PADDING}${bgcolor}${bulletcolor} %s ${c_reset}" "$bullet"
+
+}
+
+write_themes() {
+  local name="$1"
+  printf "${bgcolor}${color}%-22s %s" "$name" "$c_reset"
+}
+
+theme_output() {
+  local bgcolor="$1"
+  local bulletcolor="$2"
+  local bullet="$3"
+  local color="$4"
+  local name="$5"
+  write_bullet "$bullet"
+  write_themes "$name"
+}
+
+theme_switch() {
+  local theme="$1"
+  linebreak
+  printf "${PADDING}${switchbgcolor}${rocketcolor} ${rocket} ${currentthemecolor}%s ${c_reset}\n" "$theme"
+  linebreak
+}
+
+show_blastoff_usage() {
+  banner
+  write_tagline "Starship Theme Switcher"
+  write_usage "$usagetext" "$(basename "$0")" "$leftbracket" "$optstext" "$rightbracket"
+  linebreak
+  write_params "-t, --theme" "Set the Starship theme."
+  write_params "-l, --list" "List all available themes."
+  write_params "-h, --help" "Display this help message."
+  linebreak
+}
+
+get_starship_themes() {
+  starshippresetcheck() {
+    command starship preset --list | grep "$1"
+  }
+  starshippreset() {
+    command starship preset "$1"
+  }
+  starshippresets="$(command starship preset --list)"
+  linebreak
+  write_header "$headertext_theme"
+  for theme in "$STARSHIP_THEMES"/*.toml; do
+    local name=$(basename "$theme" .toml)
+    if [[ ! "$name" == "$(starshippresetcheck $name)" ]]; then
+      if [[ "$name" == "$currentStarshipTheme" ]]; then
+        theme_output "$currentbgcolor" "$currentcolor" "$currenttxt" "$currentthemecolor" "$name"
+      else
+        theme_output "$themebgcolor" "$bulletsymbolcolor" "$bulletsymbol" "$themecolor" "$name"
+      fi
+      linebreak
     fi
-    if [[ ! -f "$STARSHIP_CONFIG" ]]; then
-        echo "Starship config file not found: $STARSHIP_CONFIG"
-        return 1
+  done
+  linebreak
+  write_header "$headertext_preset"
+  for preset in $starshippresets; do
+    local file="$STARSHIP_THEMES/$preset.toml"
+    starshippreset "$preset" >$file
+    if [[ "$preset" == "$currentStarshipTheme" ]]; then
+      theme_output "$currentbgcolor" "$currentcolor" "$currenttxt" "$currentthemecolor" "$preset"
+    else
+      theme_output "$themebgcolor" "$bulletsymbolcolor" "$bulletsymbol" "$themecolor" "$preset"
     fi
-    return 0
-}
-
-function bannerline() {
-    local dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-    local linenumber="$1"
-    cat "$dir/blastoffbanner" | sed -n "${linenumber}p"
-}
-
-function banner() {
-    local line1="$(bannerline '1')"
-    local line2="$(bannerline '2')"
-    local line3="$(bannerline '3')"
-    printf "%-33s%s${c_reset}\n" "$PADDING" "$l1"
-    printf "%-33s%s${c_reset}\n" "$PADDING" "$l2"
-    printf "%s${bannerbgcolor}%s%s%s${c_reset}\n" "$PADDING" "$PADDING" "$line1" "$l3"
-    printf "%s${bannerbgcolor}%s%s%s${c_reset}\n" "$PADDING" "$PADDING" "$line2" "$l4"
-    printf "%s${bannerbgcolor}%s%s%s${c_reset}\n" "$PADDING" "$PADDING" "$line3" "$l4"
-}
-
-function write_tagline {
-    local tagline="$1"
-    printf "%s${taglinebgcolor}%s${taglinecolor}%-31s%s${c_reset}\n${c_reset}" "$PADDING" "$PADDING" "$tagline" "$l6"
-    printf "%-33s%s${c_reset}\n" "$PADDING" "$l7"
-}
-
-function write_usage {
-    local usage="$1"
-    local cmd="$2"
-    local left="$3"
-    local opts="$4"
-    local right="$5"
-    printf "%-3s${usagecolor}%-30s${c_reset}${rocketcolor}%s${c_reset}\n" "$PADDING" "$usage" "$l8"
-    printf "%-5s${cmdcolor}%s${c_reset} ${bracketcolor}%s${c_reset}${optscolor}%s${c_reset}${bracketcolor}%-11s${c_reset}${rocketcolor}%s${c_reset}\n" "$PADDING" "$cmd" "$left" "$opts" "$right" "$l9"
-}
-
-function write_params {
-    local paramtext="$1"
-    local desctext="$2"
-    printf "${PADDING}${parambgcolor}${paramcolor}${PADDING}%-12s${PADDING}${descbgcolor}${desccolor}${PADDING}%-26s${PADDING}${c_reset}\n" "$paramtext" "$desctext"
-}
-
-function write_header {
-    local headertext="$1"
-    printf "${PADDING}${headerbgcolor}${themeheadercolor}%s${c_reset}\n" "$headertext"
-}
-
-function write_bullet() {
-    local bullet="$1"
-    printf "${PADDING}${bgcolor}${bulletcolor} %s ${c_reset}" "$bullet"
-
-}
-
-function write_themes {
-    local name="$1"
-    printf "${bgcolor}${color}%-22s %s" "$name" "$c_reset"
-}
-function theme_output {
-    local bgcolor="$1"
-    local bulletcolor="$2"
-    local bullet="$3"
-    local color="$4"
-    local name="$5"
-    write_bullet "$bullet"
-    write_themes "$name"
-}
-
-function theme_switch {
-    local theme="$1"
     linebreak
-    printf "${PADDING}${switchbgcolor}${rocketcolor} ${rocket} ${currentthemecolor}%s ${c_reset}\n" "$theme"
-    linebreak
+  done
+  linebreak
 }
 
-function show_blastoff_usage {
-    banner
-    write_tagline "Starship Theme Switcher"
-    write_usage "$usagetext" "$(basename "$0")" "$leftbracket" "$optstext" "$rightbracket"
-    linebreak
-    write_params "-t, --theme" "Set the Starship theme."
-    write_params "-l, --list" "List all available themes."
-    write_params "-h, --help" "Display this help message."
-    linebreak
-}
+main() {
 
-function get_starship_themes {
-    starshippresetcheck() {
-        command starship preset --list | grep "$1"
-    }
-    starshippreset() {
-        command starship preset "$1"
-    }
-    starshippresets="$(command starship preset --list)"
-    linebreak
-    write_header "$headertext_theme"
-    for theme in "$STARSHIP_THEMES"/*.toml; do
-        name=$(basename "$theme" .toml)
-        if [[ ! "$name" == "$(starshippresetcheck $name)" ]]; then
-            if [[ "$name" == "$currentStarshipTheme" ]]; then
-                theme_output "$currentbgcolor" "$currentcolor" "$currenttxt" "$currentthemecolor" "$name"
-            else
-                theme_output "$themebgcolor" "$bulletsymbolcolor" "$bulletsymbol" "$themecolor" "$name"
-            fi
-            linebreak
-        fi
-    done
-    linebreak
-    write_header "$headertext_preset"
-    for preset in $starshippresets; do
-        file="$STARSHIP_THEMES/$preset.toml"
-        starshippreset "$preset" >$file
-        if [[ "$preset" == "$currentStarshipTheme" ]]; then
-            theme_output "$currentbgcolor" "$currentcolor" "$currenttxt" "$currentthemecolor" "$preset"
-        else
-            theme_output "$themebgcolor" "$bulletsymbolcolor" "$bulletsymbol" "$themecolor" "$preset"
-        fi
-        linebreak
-    done
-    linebreak
-}
+  starship_pre_check || exit 1
 
-function blastoff {
-    local help=false
-    local list=false
-    theme=""
+  local theme
+  local currentStarshipTheme=$(basename "$(readlink "$STARSHIP_CONFIG")" .toml)
 
-    starship_pre_check
-
-    while [[ $# -gt 0 ]]; do
-        case "$1" in
-        -h | --help)
-            help=true
-            shift
-            ;;
-        -l | --list)
-            list=true
-            shift
-            ;;
-        -t | --theme)
-            theme="$2"
-            shift 2
-            ;;
-        *)
-            echo "Unknown option: $1"
-            # show_blastoff_usage
-            return
-            ;;
-        esac
-    done
-
-    currentStarshipTheme=$(basename "$(readlink "$STARSHIP_CONFIG")" .toml)
-
-    if [[ "$help" == true ]]; then
-        show_blastoff_usage
-        exit
-    fi
-
-    if [[ "$list" == true ]]; then
-        get_starship_themes
-        exit
-    fi
-
-    if [[ "$theme" != "" ]]; then
-        sourcePath="$STARSHIP_THEMES/$theme.toml"
-        targetPath="$STARSHIP_CONFIG"
-
-        if [[ ! -f "$sourcePath" ]]; then
-            linebreak
-            printf "%s${switchbgcolor}${errorcolor}%s ${c_reset}${switchbgcolor}${underline}${bold}${fg_red}%s${c_reset}${switchbgcolor} ${fg_red}%s${c_reset}" "$PADDING" "$errorsymbol" "$theme" "not found."
-            linebreak
-            exit 2
-        fi
-        if [[ "$theme" == "$currentStarshipTheme" ]]; then
-            linebreak
-            printf "%s${switchbgcolor}${alertcolor}%s ${fg_flamingo}%s ${underline}${bold}${fg_rosewater}%s${c_reset}${switchbgcolor}${fg_flamingo}%s${c_reset}" "$PADDING" "$alertsymbol" "Already using theme" "$theme" "."
-            linebreak
-            exit
-        else
-            cwd=$(pwd)
-            cd "$STARSHIP_DIR" || return
-            ln -sf "themes/$theme.toml" "starship.toml"
-            currentStarshipTheme="$theme"
-            theme_switch "$currentStarshipTheme"
-            cd $cwd
-            exit
-        fi
-    fi
+  # No args?
+  [ "$#" -gt 0 ] || {
     show_blastoff_usage
+    exit
+  }
 
+  while [[ $# -gt 0 ]]; do
+    case "$1" in
+    -h | --help)
+      show_blastoff_usage
+      exit
+      ;;
+    -l | --list)
+      get_starship_themes
+      exit
+      ;;
+    -t | --theme)
+      if [[ -n "$2" ]]; then
+        theme="$2"
+        shift 2
+      else
+        printf "Current theme: %s\n" "$currentStarshipTheme"
+        exit
+      fi
+      ;;
+    *)
+      echo "Unknown option: $1"
+      # show_blastoff_usage
+      exit 1
+      ;;
+    esac
+  done
+
+  local sourcePath="$STARSHIP_THEMES/$theme.toml"
+  local targetPath="$STARSHIP_CONFIG"
+
+  if [[ ! -f "$sourcePath" ]]; then
+    linebreak
+    printf "%s${switchbgcolor}${errorcolor}%s ${c_reset}${switchbgcolor}${underline}${bold}${fg_red}%s${c_reset}${switchbgcolor} ${fg_red}%s${c_reset}" "$PADDING" "$errorsymbol" "$theme" "not found."
+    linebreak
+    exit 1
+  fi
+  if [[ "$theme" == "$currentStarshipTheme" ]]; then
+    linebreak
+    printf "%s${switchbgcolor}${alertcolor}%s ${fg_flamingo}%s ${underline}${bold}${fg_rosewater}%s${c_reset}${switchbgcolor}${fg_flamingo}%s${c_reset}" "$PADDING" "$alertsymbol" "Already using theme" "$theme" "."
+    linebreak
+    exit
+  fi
+  local cwd=$(pwd)
+  cd "$STARSHIP_DIR" || return
+  ln -sf "themes/$theme.toml" "starship.toml"
+  currentStarshipTheme="$theme"
+  theme_switch "$currentStarshipTheme"
+  cd $cwd
+  exit
 }
 
-blastoff "$@"
+main "$@"
