Update @ 04-08-2026 23:20

diff --git a/scripts/mygit b/scripts/mygit
--- a/scripts/mygit
+++ b/scripts/mygit
@@ -17,15 +17,14 @@ has() {
   command -v "$1" >/dev/null 2>&1
 }
 
-gh_user_api() {
+gituser() {
   local username
-  if has gh; then
-    username=$(gh auth status --json hosts --jq '.hosts[] | .[] | .login')
-  else
+  if has git; then
     username=$(git config --get github.user)
   fi
   if [ -z "$username" ]; then
-    fail 1 "GitHub username not found. Please set it using 'git config --global github.user <username>' or authenticate with 'gh auth login'."
+    # fail 1 "GitHub username not found. Please set it using 'git config --global github.user <username>' or authenticate with 'gh auth login'."
+    return 1
   fi
   echo "$username"
 }
@@ -36,13 +35,21 @@ in_git() {
 
 main() {
   if ! in_git; then
-    fail 1 "Not inside a git repository."
+    # fail 1 "Not inside a git repository."
+    fail 1
   fi
 
   local username
-  username=$(gh_user_api)
+  username=$(gituser)
+  local owner=$(git-it -o) || fail 1
 
-  echo "GitHub username: $username"
+  # echo "GitHub username: $username"
+  # echo "Repo owner: $owner"
+  if [[ "$username" == "$owner" ]]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 main "$@"
